import os
import subprocess
import tempfile


def generate_pdf(final_latex: str, output_pdf_path: str):
    """
    Generate a PDF from the final LaTeX resume using pdflatex.
    :param output_pdf_path: The file path where the generated PDF will be saved.
    """
    with tempfile.TemporaryDirectory() as tmpdirname:
        tex_file = os.path.join(tmpdirname, "resume.tex")
        with open(tex_file, "w") as f:
            f.write(final_latex)

        # Run pdflatex to compile the LaTeX file.
        # We run it once; for more complex documents, running twice might be needed.
        result = subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", "resume.tex"],
            cwd=tmpdirname,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )

        if result.returncode != 0:
            raise RuntimeError(f"pdflatex failed: {result.stderr.decode()}")

        pdf_file = os.path.join(tmpdirname, "resume.pdf")
        if not os.path.exists(pdf_file):
            raise FileNotFoundError("PDF was not generated by pdflatex.")

        # Write the generated PDF to the specified output path.
        with open(pdf_file, "rb") as src:
            pdf_data = src.read()
        with open(output_pdf_path, "wb") as dst:
            dst.write(pdf_data)